### ISSUE TITLE
It Might be Cool to have an example of crypto.hmac in here

### ISSUE THREAD

**Issue by joeatwork** [gtank/cryptopasta#1]
I've recently had occasion to use [crypto.hmac](https://golang.org/pkg/crypto/hmac/), and it might be worth a demo in here

**Comment by gtank** [comment]
There are HMAC functions, under `sign` - https://github.com/gtank/cryptopasta/blob/master/sign.go#L44

**Comment by joeatwork** [comment]
![Huzzah](https://media.giphy.com/media/cW5w9rwIPm06c/giphy.gif)
