### ISSUE TITLE
README shouldn't recommend using random 96-bit nonces

### ISSUE THREAD

**Issue by briansmith** [gtank/cryptopasta#10]
The readme recommends "256-bit AES-GCM with random 96-bit nonces". 256-bit AES-GCM is good, and 96-bit nonces are the safest choice. However, random nonces aren't as safe. The birthday bound is 2**48, which isn't sufficient. Instead, I recommend creating a random mask and then using a counter that is XOR'd with that mask as nonces. This is what ChaCha20-Poly1305 ciphersuites do in TLS 1.2 and later and what AES-GCM ciphersuites in TLS 1.3 and later will do. I believe this is also what OpenSSH AES-GCM cipher suites do.

**Comment by gtank** [comment]
That's a fair point, but it sounds like something that would require state (which I'm expressly trying to avoid here). Do you have a link to the implementations you're thinking about?

**Comment by briansmith** [comment]
I see. The avoidance of state is something that may be good to mention in the README.

> Do you have a link to the implementations you're thinking about?

Here's one: https://github.com/ctz/rustls/commit/f39f9b2baec6cff40613c506e375114d77d2623b#diff-4c9ae8d0d599659f5476e14edb82cbaeR230

**Comment by gtank** [comment]
Yeah, this is related to what I meant by
> Randomized nonces remove the choices around nonce generation
and management, which are another common source of error in crypto
implementations.

But I can see how it wouldn't be clear. The package is intended to stand up fairly well to a user just taking the `Encrypt()` function without any context.
