### ISSUE TITLE
Use array pointers, rather than arrays

### ISSUE THREAD

**Issue by betawaffle** [gtank/cryptopasta#11]
Passing keys as arrays rather than slices or pointers to arrays seems like a good way to spray key material all over the stack. I'd suggest using pointers in those cases so you at least have the ability to zero the memory if desired.

**Comment by gtank** [comment]
That's a really good point! I notice that @agl used array pointers in his [original ed25519 code](https://github.com/agl/ed25519/blob/master/ed25519.go#L27), but the [one that landed in `x/crypto`](https://github.com/golang/crypto/blob/master/ed25519/ed25519.go#L64) just uses byte slices. I don't know if they're equivalent in stack behavior- do you?

**Comment by betawaffle** [comment]
Byte slices are equivalent to array pointers, except that they also store a length and a capacity. In the case of known-length keys and such, length isn't particularly useful, and capacity is even less useful. The only problem with array pointers is that they necessitate extra copying if you need to go from a slice to an array pointer, and don't want to use `unsafe`.

**Comment by gtank** [comment]
Pretty clear that the right thing to do is change the arguments to array pointers- thanks for pointing this out.
