### ISSUE TITLE
https recommended ciphers

### ISSUE THREAD

**Issue by grossjo** [gtank/cryptopasta#13]
Should have samples of creating a server with strong ciphers. Seems to a common thing to do with go.

**Comment by jpillora** [comment]
See related https://blog.bracelab.com/achieving-perfect-ssl-labs-score-with-go

**Comment by gtank** [comment]
You got it, see https://github.com/gtank/cryptopasta/commit/2c3e7c36708c91dd28e4b6a83ed541e5069e86a5

@jpillora Some of those are pretty drastic usability/backward compat choices. I wouldn't suggest enabling HSTS by default, for example- it really increases the pain of getting server config or key management wrong.

**Comment by jpillora** [comment]
Yep agreed
